version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
  alert:
    image: market-bot-alert
  place-order:
    image: market-bot-place-order


